spring:
  data:
    mongodb:
      database: admin
      host: localhost
      username: admin
      password: toor
      port: 27017
      repositories:
        enabled: true
crawler:
  consumerKey: z6o0LjqUZ98ybdCn0iNl730dU
  consumerSecret: J5BwuC44n8WlglrI8cFSS1buJR6Wia6Z8SEDEKOB33fpQxYVR4
  accessToken: 3043604459-EFULmG2HmsrT8rILQolRiF1YB7jKSuVSRKEskBi
  accessTokenSecret: c2PmC9hJ6HlKEo4ijC2YZrN0qAMscjl6LVhP6mae7weyN
