spring:
  data:
    mongodb:
      database: admin
      host: localhost
      username: admin
      password: toor
      port: 27017
      repositories:
        enabled: true
crawler:
  consumerKey: z6o0LjqUZ98ybdCn0iNl730dU
  consumerSecret: J5BwuC44n8WlglrI8cFSS1buJR6Wia6Z8SEDEKOB33fpQxYVR4
  accessToken: 3043604459-VtZ8FmEfJwKBGSA6C633O0eqlM6EEm3fGzavr3g
  accessTokenSecret: FroVety3MocdNJf5SitUBR9tehU9BX5IwL2FUTGMZyjHN
